[tool.poetry]
name = "dojo-beam-transforms"
version = "2.0.0"  
description = "New Classes and AbstractPipelines"
authors = ["Gustavo Bandeira da Silva and Giovani Marin"]

packages = [
    { include = "enums" },
    { include = "pipeline_components" },
    { include = "utils" }
]