name: Call Docker Uploader Development prod

on:
  pull_request:
    branches: ["main"]
    types: [closed]

permissions:
  contents: read
  id-token: write

jobs:
  ReuseableMatrixJobForDeployment:
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        environment: [ga]
    uses: ./.github/workflows/docker_uploader.yml
    permissions:
      contents: read
      id-token: write
    with:
      environment: ${{ matrix.environment }}
    secrets: inherit
    
