name: Call Docker Uploader Dev

on:
  push:
    branches: ["feature/build_docker_workflow"]
  pull_request:
    branches: ["main"]

jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        environment: [dev]
    uses: ./.github/workflows/docker_uploader.yml
    with:
      environment: ${{ matrix.environment }}
    secrets: inherit
    