name: Call Docker Uploader Dev

on:
  push:
    branches: ["feature/build_docker_workflow"]
  pull_request:
    branches: ["main"]

jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        env: [dev]
    runs-on: ubuntu-latest
    environment: ${{ matrix.env }}

    steps:
    - uses: ./.github/workflows/docker_uploader.yml
      with:
        secrets: inherit