name: Build and Push Docker image to Artifact Registry

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      ARTIFACT_REGISTRY_KEY:
        required: true
      PROJECT_ID:
        required: true
      REGION:
        required: true

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Auth GCP Project
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.ARTIFACT_REGISTRY_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - name: Docker auth
        run: |
          gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --file DOCKERFILE_LOCATION --tag ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/dojo-beam/
        working-directory: WORKING_DIRECTORY

      - name: Push image
        run: docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/dojo-beam/
